### ISSUE TITLE
[ Utilisateur ] filtrage par checkbox

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/donneesplages#10]
**En tant qu'** Utilisateur

**je veux** pourvoir filtrer les plages selon un ou des critères "cochable"

**afin de** faire mon choix

--
Règles de gestion :
- [x] : filtrage de la couche selon un ou des critères sélectionnable via des cases à cocher
- [x] : la carte et les autres filtres doivent se mettre à jour lorsqu'une case est cochée ou décochée

**Comment by pigma** [comment]
Lorsque je clique sur une valeur celle-ci doit avoir un style qui indique qu'elle est sélectionnée. Non fonctionnel au moment ou je rédige.
