### ISSUE TITLE
[ Utilisateur ] filtrage par champ texte

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/donneesplages#11]
**En tant qu'** Utilisateur

**je veux** pourvoir filtrer les données par un champ texte avec aide à la saisie

**afin de** faire mon choix

-- 
Règles de gestion : 

- [x] : la carte et les autres filtres doivent se mettre à jour lorsqu'un texte est ajouté, ou supprimé
- [x] : Si plusieurs textes sont ajoutés dans le champs, il faut que l'ensemble des textes soient présent dans la donnée pour qu'elle soit affichée.

**Comment by pierrejego** [comment]
Comme la checkbox, est-ce que les éléments à l'intérieur d'une même filtre devrait être des ou et non des et.

Exemple, si je tape pour un nom de plage NORD, j'obtiens 4 "PLAGE NORD", si maintenant je tape SUD   j'obtiens 4 plages de plus.
Il est intéressant d'avoir les 8 et non 0 ?

**Comment by pigma** [comment]
Serait-il possible que le style du texte sélectionné soit le même que celui des textes des checkbox ?

**Comment by pigma** [comment]
> Comme la checkbox, est-ce que les éléments à l'intérieur d'une même filtre devrait être des ou et non des et.
> 
> Exemple, si je tape pour un nom de plage NORD, j'obtiens 4 "PLAGE NORD", si maintenant je tape SUD j'obtiens 4 plages de plus.
> Il est intéressant d'avoir les 8 et non 0 ?

Oui à mon avis il est préférable que sur ce champ ce soit l'opérateur "ou". Il faudrait que les choix disponible dépendent des filtres déjà sélectionnées ou si il est le premier à être sélectionné que toutes les plages soient sélectionnable et que ce soit les autres filtres qui s'adaptent (Comme évoqué précédemment). Est ce compréhensible ?

**Comment by eprouteau** [comment]
Lorsque je passe d'une valeur à une autre dans la liste des choix avec la flèche de mon clavier, dès que je passe sur une valeur, celle-ci est ajoutée

**Comment by pierrejego** [comment]
Je viens de corriger la mise à jour des valeurs du filtre texte par rapport aux autres valeurs, 
par contre je n'arrive pas à corriger le comportement du tagsinput, je n'ai pas la main sur le code. J'ai bien rajouté   confirmKeys: [13, 188] mais ça ne change rien quand on descend cela continue a selectionner la valeur
