### ISSUE TITLE
[ Utilisateur ] filtrage par combobox

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/donneesplages#12]
**En tant qu'** Utilisateur

**je veux** pouvoir filtrer les données via une combobox (liste d'éléments)

**afin de** faire mon choix

-- 
Règles de gestion : 

- [x] : la carte et les autres filtres doivent se mettre à jour lors d'une sélection ou déselection.
- [x] : Un seul champ est sélectionnable à la fois

**Comment by eprouteau** [comment]
Le bouton de réinitialisation en fonctionne pas sur le filtre en liste déroulante

**Comment by pierrejego** [comment]
Correction avec ce commit https://github.com/jdev-org/donneesplages/commit/93a413659fc515e9d6707dc515ce672b60ef53e2

Petite erreur de frappe
