### ISSUE TITLE
[ Utilisateur ] Modification des filtres 

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/donneesplages#15]
**En tant qu** 'Utilisateur

**je veux** que les données des filtres se mettent à jour en fonction des filtres déjà apportés

**afin de** faciliter mon choix

-- 
- [x] Mettre à jour la liste des filtres disponible
- [x] Choisir le mode de limitation des filtres (tout est filtré, ou uniquement les autres filtres à partir du dernier filtrage réalisé ?)

**Comment by eprouteau** [comment]
Pour le fonctionnement des filtres, dans le cas de deux filtres cases à cocher, le premier filtre coché devient le filtre principal et laisse visible tout ses choix, et c'est l'autre ou les autres filtres qui varies en fonction des choix réalisés sur le premier filtre. J'espère que c'est compréhensible (ex : https://www.leroymerlin.fr/v3/p/produits/salle-de-bains/accessoires-et-miroirs-de-salle-de-bains/miroir-de-salle-de-bains-l1308217405?page=1)

**Comment by eprouteau** [comment]
Le filtrage des choix des filtres lorsqu'un filtre est activé, ne fonctionne pas avec un geojson provenant de qgis ou fme. Testé avec les données plages et autres données du geoserver
 converties via qgis ou fme.
[plage_fme.zip](https://github.com/jdev-org/donneesplages/files/4567686/plage_fme.zip)

**Comment by pierrejego** [comment]
@eprouteau je viens de faire le test avec le fichier fme, aucun soucis de mon côté. Tu as un message d'erreur dans la console ?

**Comment by eprouteau** [comment]
Je viens de le mettre sur la plateforme PIGMA pour tester et même comportement : https://www.pigma.org/public/visualiseur/mviewer/?config=apps/dev_plage/dev_plage.xml

J'ai vidé tout les caches de mon navigateur

Je n'ai aucuns messages dans la console

**Comment by eprouteau** [comment]
Je viens de faire un clone de ton git sur mon localhost ton fichier de config donneesplage1.xml ne pointait pas vers le custom layer plage1.js. Je l'ai fais pointé dessus et je reproduis le problème.
