### ISSUE TITLE
Erreur au démarage

### ISSUE THREAD

**Issue by eprouteau** [jdev-org/donneesplages#23]
Voici la capture de l'erreur que j'ai au démarrage avec la couche provenant de geoserver. Erreur similaire que j'évoquais avec un geojson en local provenant de FME ou Qgis

![image](https://user-images.githubusercontent.com/1401902/81936013-cac84180-95f1-11ea-9da2-e804e154203f.png)

Firefox me semble plus sensible

**Comment by pierrejego** [comment]
ça semble lié à une régression du passage en openlayers6, pas facile de comprendre vu comment ça n'arrive pas souvent

**Comment by eprouteau** [comment]
L'affiche du filtre est très aléatoire lors d'un rafraîchissement de la page. C'est le retour global des gens qui ont utilisé l'appli covid

**Comment by pierrejego** [comment]
Tout juste corrigé :) j'ai changé complètement la gestion des events.
J'ai essayé plein de navigateur et de refresh, je n'ai plus l'erreur. Si jamais ça se reproduit je veux bien une description des étapes pour y arriver

**Comment by eprouteau** [comment]
Ok je déploie sur notre serveur

**Comment by pierrejego** [comment]
Attends je refais un test, j'ai un soucis une fois déployé sur gis.jdev.fr

**Comment by pierrejego** [comment]
Cette fois c'est bon tu peux mettre à jour chez toi
