### ISSUE TITLE
[ Utilisateur ] Filtrer des données sur une couche

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/donneesplages#3]
**En tant qu'** utilisateur

**je veux** filtrer les données visibles à l'écran par une interface graphique

**afin de** faciliter mes recherches

-- 
- [x] : Définir le point d'entrée du module de filtrage (dans la légende, ou comme un outils bouton sur la droite)
- [x] : Définir le positionnement de la fenêtre de filtrage

**Comment by pigma** [comment]
Lorsque que je clique sur le bouton pour activer le module de filtre, celui-ci reste gris lorsque je clique dessus pour fermer le module de filtre. Il faut que je clique sur la carte afin qu'il apparaisse désactivé.

**Comment by pierrejego** [comment]
La fenêtre est maintenant déplaçable sur l'écran
