### ISSUE TITLE
Problème d'affichage des données filtrées

### ISSUE THREAD

**Issue by pigma** [jdev-org/donneesplages#31]
Pierre,

Lorsque j'utilise le filtre il zoom sur les entités mais laisse affiché toutes les entités.

reproduit sur : https://gis.jdev.fr/mviewer/?config=apps/donneesplages/donneesplages3.xml

**Comment by pierrejego** [comment]
Je reproduis aussi, je viens de passer en pas à pas pour comprendre, mais pour l'instant je ne vois pas d'ou cela peut venir. 
Le filtrage fonctionne bien, le zoom aussi, par exemple si je choisi douche ça zoom bien sur la zone ou il y a des plages avec des douches. Par contre il y a toutes les données affichées.
ça semble être le refresh sur le cluster qui ré-affiche toutes les entités.  Je vous tiens au courant dès que j'ai trouvé la cause et une correction

**Comment by pigma** [comment]
Super, Merci

**Comment by Gaetanbrl** [comment]
Il doit y avoir un soucis avec cette ligne qui doit masquer la feature filtrée : 

https://github.com/jdev-org/donneesplages/blob/964aafa5ac42c27137ec504f4159033431a61450/addons/filter/js/filter.js#L750


On souhaite masquer la feature via un style null, je pense que c'est bien ce que fait le code.
Mais c'est le cluster qui est représenté. Je pense que le cluster va tout de même inclure cette feature  et se représenter car il ne prend pas en compte le style de la feature.

**Comment by Gaetanbrl** [comment]
Correctif testable sur la branche issue-31 avant PR.

**Comment by pigma** [comment]
Salut Gaetan,

Je viens de tester et ca me semble OK :)

**Comment by pierrejego** [comment]
Mergé :) merci @Gaetanbrl 

Je vais commencer le report pour la communauté du coup.
