### ISSUE TITLE
[ Administrateur ] Configuration du filtrage sur une couche

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/donneesplages#4]
**En tant qu'** administrateur

**je veux** pouvoir configurer dans le fichier de l'application la liste des attributs pouvant être filtrés sur une couche

**afin de** permettre aux utilisateurs d'y avoir accès

-- 
- [x] : Ajout des paramètres dans le fichier de l'application
- [x] : Ajout de la lecture des paramètres dans le coeur de l'application
- [x] : Prise en compte des paramètres dans la fonctionnalité de filtrage ajoutée
- [x] : Mise en place de règles de gestion multi-attributaire

**Comment by pierrejego** [comment]
Avec la solution proposée {attribut: type} je rencontre deux soucis.
Tout d'abord pour que cela soit pris en compte comme un object Json il faudraut {"attribut": "type"} ce qui n'est pas possible dans cette partie de configuration.
Deuxième point il me manque le label à afficher au dessus du filtrage. Par exemple 
{equipements_publics: checkbox},  je n'ai pas l'information  Equipement public à afficher au dessus.

Je vous propose donc de revoir un peu cette partie de configuration en ajoutant un label, et en modifiant la syntaxe pour pouvoir parser facilement les paramètres.

**Comment by pigma** [comment]
L'ajout d'un label pour le filtre dans le fichier de configuration me parait pertinent car le nom du champs n'est pas toujours "français"

**Comment by pierrejego** [comment]
C'est fait, mis en place dans la conf du json

```
  "options": {
    "title": "filtrer",
    "layers": [{
      "layerId": "plage",
      "filter": [{
          "attribut": "grand_territoire",
          "type": "checkbox",
          "label": "Grand térritoire"
        },
        {
          "attribut": "equipements_services",
          "type": "checkbox",
          "label": "Service"
        },
        {
          "attribut": "nature_baignade",
          "type": "combobox",
          "label": "Nature de baignade"
        },
        {
          "attribut": "commune",
          "type": "textbox",
          "label": "Commune"
        },
        {
          "attribut": ["date_ouverture", "date_fermeture"],
          "type": "date",
          "label": "Ouverte le"
        }
      ]
    }]
  }
```

**Comment by eprouteau** [comment]
Possibilité d'ajouter un alias pour le nom de la couche soit dans le fichier de config du filtre ou récupération de son nom dans le fichier de config général car l'id de la couche peux ne pas être très parlant lorsque que l'on choisi la couche à filtrer. A voir quelle solution est la plus performante.
