### ISSUE TITLE
[ Utilisateur ] remise à zéro des critères de filtres

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/donneesplages#8]
**En tant qu'** Utilisateur

**je veux** pouvoir remettre à zéro les filtres réalisés

**afin de** refaire une recherche sur d'autres critères

-- 
- [x] : ajout d'une croix sur chaque filtre
- [x] : ajout d'une croix pour remise à zéro de l'ensemble des filtres
- [x] : choisir le meilleur choix pour une utilisation simple sur mobile

**Comment by eprouteau** [comment]
Si je clique 4 fois sur une valeur, il faut cliquer 4 fois sur la croix de réinitialisation pour avoir une remise à zero des données.

Ne faut-il pas se limiter à une réinitialisation globale de tout les filtres et que pour chaque filtre l'utilisateur devra cliquer sur le filtre sélectionné (mis en surbrillance) pour le désactiver ?

**Comment by pierrejego** [comment]
Si tu as raison, c'est en cours. J'ai du revoir la structure du code pour me permettre de savoir quels filtres étaient actifs ou non pour recocher les cases, sélectionner les combox et pouvoir avoir une couleur différente en fonction si c'est sélectionné ou non. Je pense avoir fini le refactoring et les tests d'ici ce soir, Tu devrais y voir plus clair demain matin
